import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import GlobalAutoPilot from '../components/GlobalAutoPilot';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script src="https://unpkg.com/@ffmpeg/ffmpeg@0.12.6/dist/umd/ffmpeg.js"></script>
      </head>
      <body className="min-h-full flex flex-col bg-gradient-to-br from-slate-50 to-slate-100 text-slate-900 selection:bg-indigo-500 selection:text-white">
        <nav className="sticky top-0 z-50 w-full backdrop-blur-xl bg-white/70 border-b border-white/20 shadow-[0_4px_30px_rgba(0,0,0,0.03)] transition-all duration-300">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between h-16 items-center">
              <div className="flex items-center gap-8">
                <div className="flex-shrink-0 flex items-center group cursor-pointer">
                  <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-lg shadow-indigo-500/30 group-hover:shadow-indigo-500/50 transition-all duration-300 mr-3">
                    <svg className="w-5 h-5 text-white transform group-hover:rotate-12 transition-transform duration-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                    </svg>
                  </div>
                  <span className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 to-purple-600 tracking-tight">
                    AI Studio
                  </span>
                </div>
                <div className="hidden sm:flex sm:space-x-1">
                  <Link href="/" className="px-4 py-2 rounded-full text-sm font-bold text-slate-700 hover:text-indigo-600 hover:bg-indigo-50/80 transition-all duration-200">
                    Dashboard
                  </Link>
                  <Link href="/poster" className="px-4 py-2 rounded-full text-sm font-semibold text-slate-700 hover:text-indigo-600 hover:bg-indigo-50/80 transition-all duration-200 flex items-center gap-2">
                    <span>📅</span> Auto-Poster
                  </Link>
                  <Link href="/studio" className="px-4 py-2 rounded-full text-sm font-semibold text-slate-700 hover:text-indigo-600 hover:bg-indigo-50/80 transition-all duration-200 flex items-center gap-2">
                    <span>✨</span> AI Studio
                  </Link>
                  <Link href="/database" className="px-4 py-2 rounded-full text-sm font-semibold text-slate-700 hover:text-indigo-600 hover:bg-indigo-50/80 transition-all duration-200 flex items-center gap-2">
                    <span>🗄️</span> Database
                  </Link>
                  <Link href="/products" className="px-4 py-2 rounded-full text-sm font-semibold text-slate-700 hover:text-indigo-600 hover:bg-indigo-50/80 transition-all duration-200 flex items-center gap-2">
                    <span>🖼️</span> Gallery
                  </Link>
                  <Link href="/raw-data" className="px-4 py-2 rounded-full text-sm font-semibold text-slate-700 hover:text-red-600 hover:bg-red-50/80 transition-all duration-200 flex items-center gap-2 border border-red-100">
                    <span>🕵️</span> Unidentified Data
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </nav>
        <main className="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6 lg:p-8 animate-in fade-in slide-in-from-bottom-4 duration-700 ease-out">
          <GlobalAutoPilot />
          {children}
        </main>
      </body>
    </html>
  );
}
